#!/usr/bin/env bash

#
# Install git
#

SUDO=${CH_SUDO:-sudo}

if [ -x "$(command -v pacman)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO pacman -S --needed --noconfirm git
elif [ -x "$(command -v apt)" ] && [ ! -x "$(command -v git)" ]; then
  $SUDO apt install git -y
fi

#
# Clone cathook
#

git clone --depth 1 https://github.com/Catmasta101/mastahook

#
# Run cathook's install all script
#

pushd mastahook
bash ./install-all
popd
